"""
Export Tools - PDF, Excel, and Shareable Reports
Week 1 Critical Improvement: Export/Share Features
"""

import json
import io
from datetime import datetime
from typing import Dict, Any, Optional

def export_strategy_to_json(strategy_data: Dict[str, Any], company_name: str) -> str:
    """Export strategy to JSON format"""
    export_data = {
        "company": company_name,
        "exported_at": datetime.now().isoformat(),
        "strategy": strategy_data
    }
    return json.dumps(export_data, indent=2)

def export_strategy_to_csv(strategy_data: Dict[str, Any], company_name: str) -> str:
    """Export strategy summary to CSV format"""
    lines = [
        "Key,Value",
        f"Company,{company_name}",
        f"Exported At,{datetime.now().isoformat()}",
    ]

    for key, value in strategy_data.items():
        if isinstance(value, list):
            for i, item in enumerate(value[:5]):
                lines.append(f"{key}_{i},{item}")
        elif isinstance(value, dict):
            for k, v in value.items():
                lines.append(f"{key}_{k},{v}")
        else:
            lines.append(f"{key},{value}")

    return "\n".join(lines)

def create_strategy_summary_text(
    company: str,
    description: str,
    strategy: Dict[str, Any]
) -> str:
    """Create a text summary of the strategy"""

    summary = f"""
STRATEGIC ANALYSIS REPORT
{'=' * 60}

COMPANY: {company}
DESCRIPTION: {description}
GENERATED: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

{'=' * 60}

MARKET ANALYSIS
{'-' * 60}

"""

    # Market metrics
    if 'tam' in strategy:
        summary += f"Total Addressable Market (TAM): ${strategy['tam']:,.0f}M\n"

    if 'growth_rate' in strategy:
        summary += f"Annual Growth Rate: {strategy['growth_rate']}\n"

    if 'market_segments' in strategy:
        summary += f"\nMarket Segments:\n"
        for segment in strategy.get('market_segments', [])[:5]:
            summary += f"  - {segment}\n"

    # Opportunities
    if 'opportunities' in strategy:
        summary += f"\nMarket Opportunities:\n"
        for opp in strategy.get('opportunities', [])[:5]:
            summary += f"  - {opp}\n"

    # Barriers
    if 'entry_barriers' in strategy:
        summary += f"\nEntry Barriers:\n"
        barriers = strategy.get('entry_barriers', [])
        if isinstance(barriers, list):
            for barrier in barriers[:5]:
                summary += f"  - {barrier}\n"
        else:
            summary += f"  - {barriers}\n"

    # Funding needs
    if 'investment_needed' in strategy:
        summary += f"\nEstimated Investment Needed: ${strategy['investment_needed']:,.0f}M\n"

    # Timeline
    if 'timeline_to_profitability' in strategy:
        summary += f"Timeline to Profitability: {strategy['timeline_to_profitability']}\n"

    summary += f"\n{'=' * 60}\n"
    summary += f"Report generated by AI Business Tools\n"
    summary += f"www.aibusinesstools.com\n"

    return summary

def create_html_report(
    company: str,
    description: str,
    founder: str,
    strategy: Dict[str, Any]
) -> str:
    """Create an HTML version of the strategy report"""

    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{company} - Strategy Report</title>
        <style>
            body {{
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
                max-width: 900px;
                margin: 0 auto;
                padding: 2rem;
                background: #f5f5f5;
                color: #333;
            }}
            .header {{
                background: linear-gradient(135deg, #1f77b4 0%, #ff6b35 100%);
                color: white;
                padding: 2rem;
                border-radius: 8px;
                margin-bottom: 2rem;
            }}
            .header h1 {{
                margin: 0;
                font-size: 2.5rem;
            }}
            .header p {{
                margin: 0.5rem 0 0 0;
                opacity: 0.9;
            }}
            .section {{
                background: white;
                padding: 2rem;
                border-radius: 8px;
                margin-bottom: 1.5rem;
                box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            }}
            .section h2 {{
                color: #1f77b4;
                border-bottom: 2px solid #ff6b35;
                padding-bottom: 0.5rem;
                margin-top: 0;
            }}
            .metric {{
                display: inline-block;
                margin: 1rem 1rem 1rem 0;
                padding: 1rem;
                background: #f0f2f6;
                border-radius: 8px;
            }}
            .metric-label {{
                display: block;
                font-size: 0.9rem;
                color: #666;
                margin-bottom: 0.25rem;
            }}
            .metric-value {{
                display: block;
                font-size: 1.5rem;
                font-weight: bold;
                color: #1f77b4;
            }}
            .list-item {{
                margin: 0.75rem 0;
                padding-left: 1.5rem;
                position: relative;
            }}
            .list-item:before {{
                content: "•";
                position: absolute;
                left: 0;
                color: #ff6b35;
                font-weight: bold;
            }}
            .footer {{
                text-align: center;
                padding: 2rem;
                color: #666;
                font-size: 0.9rem;
            }}
            .generated {{
                color: #999;
                font-size: 0.85rem;
            }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>{company}</h1>
            <p>{description}</p>
            <p style="margin-top: 1rem;">Founder: {founder} | Generated: {datetime.now().strftime('%B %d, %Y')}</p>
        </div>

        <div class="section">
            <h2>Market Analysis</h2>
    """

    # Add metrics
    if 'tam' in strategy:
        html += f"""
            <div class="metric">
                <span class="metric-label">Market Size (TAM)</span>
                <span class="metric-value">${strategy['tam']:,.0f}M</span>
            </div>
        """

    if 'growth_rate' in strategy:
        html += f"""
            <div class="metric">
                <span class="metric-label">Annual Growth</span>
                <span class="metric-value">{strategy['growth_rate']}</span>
            </div>
        """

    # Market segments
    if 'market_segments' in strategy:
        html += "<h3>Market Segments</h3>"
        for segment in strategy.get('market_segments', [])[:5]:
            html += f'<div class="list-item">{segment}</div>'

    # Opportunities
    if 'opportunities' in strategy:
        html += "<h3>Opportunities</h3>"
        for opp in strategy.get('opportunities', [])[:5]:
            html += f'<div class="list-item">{opp}</div>'

    html += """
        </div>

        <div class="section">
            <h2>Key Metrics</h2>
    """

    # Additional metrics
    if 'investment_needed' in strategy:
        html += f"""
            <div class="metric">
                <span class="metric-label">Funding Required</span>
                <span class="metric-value">${strategy['investment_needed']:,.0f}M</span>
            </div>
        """

    if 'timeline_to_profitability' in strategy:
        html += f"""
            <div class="metric">
                <span class="metric-label">Path to Profitability</span>
                <span class="metric-value">{strategy['timeline_to_profitability']}</span>
            </div>
        """

    # Entry barriers
    if 'entry_barriers' in strategy:
        html += "<h3>Entry Barriers</h3>"
        barriers = strategy.get('entry_barriers', [])
        if isinstance(barriers, list):
            for barrier in barriers[:5]:
                html += f'<div class="list-item">{barrier}</div>'
        else:
            html += f'<div class="list-item">{barriers}</div>'

    html += """
        </div>

        <div class="section">
            <h2>Next Steps</h2>
            <div class="list-item">Analyze competitive landscape</div>
            <div class="list-item">Define pricing strategy</div>
            <div class="list-item">Plan go-to-market approach</div>
            <div class="list-item">Develop funding strategy</div>
        </div>

        <div class="footer">
            <p class="generated">Generated by <strong>AI Business Tools</strong></p>
            <p>Your AI co-founder for strategic thinking</p>
            <p>Visit: www.aibusinesstools.com</p>
        </div>
    </body>
    </html>
    """

    return html

def create_shareable_link_data(
    company: str,
    strategy: Dict[str, Any]
) -> Dict[str, Any]:
    """Create data structure for shareable links"""

    return {
        "company": company,
        "created_at": datetime.now().isoformat(),
        "strategy_snapshot": {
            "tam": strategy.get('tam'),
            "growth_rate": strategy.get('growth_rate'),
            "opportunities_count": len(strategy.get('opportunities', [])),
            "market_segments_count": len(strategy.get('market_segments', []))
        },
        "share_id": hash(f"{company}_{datetime.now().isoformat()}") % 1000000
    }
